Repository sleddog/methods, pull requests merged in 2019-04, with the labels that each got.

#77 Jaserost Proposal
  projects/fbb-service/FellowshipOfTheCode/README.md
  projects/fbb-service/FellowshipOfTheCode/api.yaml
Labels: Proposal

#81 Team Group Project Proposal - GET
  projects/carnival_guess/RAT/README.md
  projects/carnival_guess/RAT/api.yaml
  projects/carnival_guess/RAT/app.py
  projects/carnival_guess/RAT/templates/home.html
Labels: Proposal

#89 Collaborated FizzBuzzBazz in C
  projects/fizzbuzz/C/combined/FBB.c
  projects/fizzbuzz/C/combined/README.md
  projects/fizzbuzz/C/combined/fizzBuzzBazz.sh
  projects/fizzbuzz/C/combined/runTests.sh
  projects/fizzbuzz/C/combined/unitTest.c
Labels: Collaboration

#100 Alphabetized the list and added MS-DOS article
  ARTICLES.md
Labels: article

#114 Ideas for upcoming panel discussion
  PANEL.md
Labels: Panel Ideas
